[project]
name = "mcp-server-deployment"
version = "0.1.0"
description = "MCP server with an addition tool"
readme = "README.md"
authors = [
    { name = "ishantchoukse", email = "ishantchoukse@fico.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=2.2.0",
]

[project.scripts]
mcp-server-deployment = "mcp_server_deployment.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
