[project]
name = "mcp-server-deployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ishantchoukse", email = "ishantchoukse@fico.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=2.2.0",
]

[project.scripts]
mcp-server-deployment = "mcp_server_deployment:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
